# Filesystem
GENERATED_FOLDER = 'voices'
MODELS_FOLDER = 'models'
ONSET_FILE = 'onset.json'

# Sequence data & generate
BLOCK_SEC = 120
DURATIONS = [100, 500, 1000, 2000, 4000]
SILENCE_CLASS = 0

# Feature vector
NUM_CLASSES_DURATIONS = len(DURATIONS)
NUM_CLASSES_DYNAMICS = 5
NUM_CLASSES_SOUNDS = 99

# Hyperparameters
BATCH_SIZE = 32
DATA_SPLIT = 0.3
DROPOUT = 0.1
EPOCHS = 50
NUM_LAYERS = 2
NUM_UNITS = 256
SEQ_LEN = 3

# Session
INTERVAL_SEC = 0.75
PENALTY = 3
SAMPLE_RATE = 44100
TEMPERATURE = 1.0
THRESHOLD_DB = -80
VOLUME = 1.0

# Soundcard
INPUT_CHANNEL = 0
INPUT_DEVICE = 0
OUTPUT_CHANNEL = 0
OUTPUT_DEVICE = 0

# OSC Server
OSC_ADDRESS = '127.0.0.1'
OSC_PORT = 5005
